version: 0.2

phases:
  install:
    commands:
      - echo Logging in
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - cd demo     
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
