version: 0.2

phases:
  install:
    commands:
      - echo Logging in
  build:
    commands:
      - echo Build started on `date`
      - cd demo  
      - .\mvnw.cmd spring-boot:run          
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
